version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notifications
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit_pass

  notifications-service:
    image: node:18
    container_name: notifications-service
    restart: always
    working_dir: /app
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"

volumes:
  mysql_data:
